---
name: CI

on:
  - push

jobs:
  lint:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@5.0.2
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: windows-2019
    strategy:
      matrix:
        image:
          - windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@5.0.2
        with:
          image: "${{ matrix.image }}"
          options: parallel
          scenario: my_specific_scenario
