name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip install python-vagrant ansible yamllint ansible-lint passlib lxml xmltodict jmespath pywinrm      
      
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      
      - name: Show Vagrant version
        run: vagrant --version
        
      - name: Run vagrant up
        run: vagrant up
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
